services:
  php:
    image: php:8.4-fpm
    build: ./php
    container_name: docker_php
    volumes:
      - ./src:/var/www/html
      - ./php/conf.d/99-xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
    environment:
      - MYSQL_HOST=host.docker.internal
      - MYSQL_USER=alumno
      - MYSQL_PASSWORD=alumno
      - MYSQL_DB=employees
      - MYSQL_PORT=3306
      - MONGODB_HOST=host.docker.internal
      - MONGODB_USER=alumno
      - MONGODB_PASSWORD=alumno
      - MONGODB_DB=test
      - MONGODB_PORT=27017

  nginx:
    image: nginx:latest
    container_name: docker_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

