name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP with composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, intl
          tools: composer

      - name: Install dependencies with composer
        working-directory: ./src
        run: composer install --no-dev --optimize-autoloader

      - name: upload public files to htdocs/
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./src/public/
          server-dir: /htdocs/
          state-name: ftpdeploy-public

      - name: Prepare src without public
        run: |
          mkdir temp_src
          shopt -s extglob
          cp -r src/!(public) temp_src/
        shell: bash
